version: 2

models:
  - name: daily_temperatures # Remplace par le nom exact de ton modèle si nécessaire
    description: "Description de ton modèle"
    columns:
      - name: date
        tests:
          - unique
          - not_null